Reorganize course information + Updated schedule
UCB-stat-159-s23/site pull request #2
Opened 2023-02-02 04:25 UTC by facusapienza21

I have re-accommodated the order of the information on the course website. I put most of the information in different tabs inside a section called `Overview`, which allow us to split general information, references, syllabus, and reading assignments. 

I have also updated the course schedule based on the current plan for the semester, at least for the next weeks.

2023-02-03 04:00 UTC, facusapienza21 commented
@fperez I am still trying to make #3 work, but for the moment you can see the changes in the website from the [JB deployed from my fork](https://facusapienza21.github.io/stat159-site/overview/ra.html).

2023-02-03 16:39 UTC, fperez approved these changes
Excellent, many thanks!!

2023-02-03 16:45 UTC, fperez requested changes
Once these small fixes are in, please go ahead and merge. Thanks!!

2023-02-03 16:45 UTC, fperez commented on overview/overview.md
> +**Teacher Assistant**: [Facundo Sapienza](https://statistics.berkeley.edu/people/facu-sapienza)
s/Teacher/Teaching/

2023-02-03 16:45 UTC, fperez commented on overview/ra.md
> +Every week, each student is ask to read and discuss a series of reading assignments. The topics of the reading assignments include reproducibitity in science, open source practices, and applications
s/ask/asked/

2023-02-03 16:45 UTC, fperez commented on overview/ra.md
> +Every week, each student is ask to read and discuss a series of reading assignments. The topics of the reading assignments include reproducibitity in science, open source practices, and applications
s/between/among/

2023-02-03 16:45 UTC, fperez commented on overview/ra.md
> +You have to submit a total of two paragraphs per each separate article. The first is a summary paragraph and the second must highlight an important idea of the reading. This last one can be focused i
s/catched/caught/

2023-02-03 16:45 UTC, fperez commented on overview/ra.md
> +You have to submit a total of two paragraphs per each separate article. The first is a summary paragraph and the second must highlight an important idea of the reading. This last one can be focused i
s/lenght/length/

2023-02-03 16:45 UTC, fperez commented on overview/ra.md
> +You have to submit a total of two paragraphs per each separate article. The first is a summary paragraph and the second must highlight an important idea of the reading. This last one can be focused i
Missing end period.

2023-02-03 16:45 UTC, fperez commented on overview/ra.md
> +You will submit your reading assignments in bCourses. Reading assignments will be due every Wednesday at 9pm (Exception: the first one will be due _Thursday Jan 26_). No later reading assignments wil
s/no later/no late/

2023-02-03 16:45 UTC, fperez commented on overview/ra.md
> +You will submit your reading assignments in bCourses. Reading assignments will be due every Wednesday at 9pm (Exception: the first one will be due _Thursday Jan 26_). No later reading assignments wil
s/medical exception/medical situation or other documented major emergency/

2023-02-03 16:45 UTC, fperez commented on overview/ra.md
> +You will submit your reading assignments in bCourses. Reading assignments will be due every Wednesday at 9pm (Exception: the first one will be due _Thursday Jan 26_). No later reading assignments wil
s/medical proof/supporting evidence/

2023-02-03 16:47 UTC, fperez commented
Sorry about a small confusion above - at first I thought the ReadTheDocs config change was a separate PR and meant to approve that change, before realizing that it was part of the main PR. It was just me not reading carefully.

This PR should be merged only after making the few small fixes I highlighted in my review.

Thanks for the great work @facusapienza21!

2023-02-04 21:16 UTC, facusapienza21 reviewed
Incorporated gramma check

2023-02-04 21:17 UTC, merged